// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD46VEJlur3gWw5JWH6SkKEj4Br1Y6uMx8',
    appId: '1:273578807446:web:0b318d01f7488352f0b2b7',
    messagingSenderId: '273578807446',
    projectId: 'khatabookapp-aa601',
    authDomain: 'khatabookapp-aa601.firebaseapp.com',
    storageBucket: 'khatabookapp-aa601.appspot.com',
    measurementId: 'G-81N3LZCM0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFHOTPP_aho9vwFyK4TCoZxRR4_ghPtLw',
    appId: '1:273578807446:android:405638fa2209d8e0f0b2b7',
    messagingSenderId: '273578807446',
    projectId: 'khatabookapp-aa601',
    storageBucket: 'khatabookapp-aa601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5v28V_cDGDYUk9SEdfu9tCWfCO9qTRI8',
    appId: '1:273578807446:ios:5157e0e1c1b3f51cf0b2b7',
    messagingSenderId: '273578807446',
    projectId: 'khatabookapp-aa601',
    storageBucket: 'khatabookapp-aa601.appspot.com',
    iosBundleId: 'com.example.khataApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5v28V_cDGDYUk9SEdfu9tCWfCO9qTRI8',
    appId: '1:273578807446:ios:5157e0e1c1b3f51cf0b2b7',
    messagingSenderId: '273578807446',
    projectId: 'khatabookapp-aa601',
    storageBucket: 'khatabookapp-aa601.appspot.com',
    iosBundleId: 'com.example.khataApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD46VEJlur3gWw5JWH6SkKEj4Br1Y6uMx8',
    appId: '1:273578807446:web:3820c138ad6ef0aff0b2b7',
    messagingSenderId: '273578807446',
    projectId: 'khatabookapp-aa601',
    authDomain: 'khatabookapp-aa601.firebaseapp.com',
    storageBucket: 'khatabookapp-aa601.appspot.com',
    measurementId: 'G-DFX7TE52XK',
  );
}
